---
- name: play1
  hosts: servers
  remote_user: ec2-user
  become: yes
  tasks:
  - name: install nginx
    command: apt install -y nginx
  - name: start nginx
    service:
      name: nginx
      state: started